import type { Competency, GeneratedQuestion, RoleSetupInput } from '../types';

export function toMarkdown({
  roleSetup,
  competencies,
  questions,
  candidateName,
}: {
  roleSetup: RoleSetupInput;
  competencies: Competency[];
  questions: GeneratedQuestion[];
  candidateName?: string | null;
}): string {
  const lines: string[] = [];
  const total = questions.reduce((sum, q) => sum + q.estimatedMinutes, 0);

  lines.push(`# Interviewer Briefing Pack — ${roleSetup.jobTitle}`);
  lines.push('');
  lines.push(`**${roleSetup.seniorityLevel}** · ${roleSetup.interviewRound}`);
  if (roleSetup.teamContext) lines.push(`_${roleSetup.teamContext}_`);
  lines.push('');
  lines.push(`${questions.length} questions · ~${total} minutes`);
  lines.push('');

  lines.push('## Target competencies');
  lines.push('');
  for (const c of competencies) {
    lines.push(`- **${c.name}** — from the JD: "${c.jdEvidence}"`);
  }
  lines.push('');

  lines.push('## Compliance reminder');
  lines.push('');
  lines.push(
    'Ask every candidate the same standard questions and score against the rubric. Avoid family status, age, national origin, religion, and disability. Do not use graduation years as an age proxy. Record specific evidence for every score.',
  );
  lines.push('');

  const render = (q: GeneratedQuestion, n: number) => {
    lines.push(`### ${n}. ${q.question}`);
    lines.push('');
    lines.push(`**Competency:** ${q.competency} · **Time:** ~${q.estimatedMinutes} min`);
    lines.push('');
    lines.push(`**Why this question:** ${q.reasoning}`);
    lines.push('');
    if (q.jdEvidence) lines.push(`> From the job description: "${q.jdEvidence}"`);
    if (q.resumeEvidence) lines.push(`> From the resume: "${q.resumeEvidence}"`);
    lines.push('');
    lines.push('**Follow-ups**');
    for (const f of q.followUps) lines.push(`- ${f}`);
    lines.push('');
    lines.push('**Scoring rubric**');
    lines.push(`- **1 —** ${q.scoringRubric.score1}`);
    lines.push(`- **3 —** ${q.scoringRubric.score3}`);
    lines.push(`- **5 —** ${q.scoringRubric.score5}`);
    lines.push('');
    lines.push('**Red flags**');
    for (const f of q.redFlags) lines.push(`- ${f}`);
    lines.push('');
    if (q.biasCheck.status === 'warning' && q.biasCheck.note) {
      lines.push(`⚠️ **Compliance note:** ${q.biasCheck.note}`);
      lines.push('');
    }
  };

  const standard = questions.filter((q) => q.source === 'standard');
  const personalized = questions.filter((q) => q.source === 'personalized');

  lines.push('## Interview structure');
  lines.push('');
  standard.forEach((q, i) => render(q, i + 1));

  if (personalized.length) {
    lines.push(`## Resume-specific questions${candidateName ? ` — ${candidateName}` : ''}`);
    lines.push('');
    personalized.forEach((q, i) => render(q, standard.length + i + 1));
  }

  lines.push('---');
  lines.push('');
  lines.push('_Generated by InterviewCopilot._');

  return lines.join('\n');
}
